spring.application.name=e-commerce
server.port=9090
#spring.application.name=BankingPackage
server.tomcat.max-threads=200

## multiple application properties calling
#spring.profiles.active=local
spring.profiles.active=dev
#spring.profiles.active=prod
